### PR TITLE
Add a robospice-retrofit2 module to support a new Retrofit of version 2.0 and up

### PR DESCRIPTION
**Pull request by mykolaj**
Add a robospice-retrofit2 module to support a Retrofit version 2.0 and up

### CODE REVIEW

**Comment by rciovati** [comment]
Hey @mykolaj, thanks for the pull request! Would you mind to send it against the `master` branch?

**Comment by rciovati** [comment]
I gave a quick look at the code. Not sure if I like the 2 suffix both in the package and in the classe names.

**Comment by mykolaj** [comment]
No problemo. [Here](https://github.com/stephanenicolas/robospice/pull/455) it is.
Also, i don't like this "2" suffix either, and is opened to suggestions. But my creativity leaved me with that alone. :)

**Comment by rciovati** [comment]
Closing in favor of #455

**Pull request closed without merging**
