### PR TITLE
changed visibility of method createRequestRunner()

### PR DESCRIPTION
**Pull request by orwir**
This allow to use own implementation of RequestRunner.

### CODE REVIEW

**Comment by guofengzh** [comment]
+1

**Comment by NightmaresSeller** [comment]
+1
We use Robospice in our app for requests that do not rely on network as well, just because of Robospice's handy notification system. But unfortunately, DefaultRequestRunner does not allow to execute requests when network is down. This pull request will allow to override RequestRunner behavior correctly without ugly hacks we forced to use.

**Comment by stephanenicolas** [comment]
This PR should get merged in. Unfortunatelly I don't have time to do it and
will be working on RS only by the end of this year.
If anyone else can merge it, and release, that would be nice.

S.

2015-09-08 11:49 GMT-04:00 NightmaresSeller <notifications@github.com>:

**Comment by softwaremaverick** [comment]
I'm hoping that this is all I needed to do. But the one line commit seemed indeed fine and I'm hoping that clicking that button merged it into the correct branch. 

This commit along with some others are very old though but I've finally got round to logging in to take a punt at some. Only however because my password got hacked so came back to Github in the hope little damage had been done.

Anyway, thanks @orwir for the commit. It definitely is a worthwhile one.

**Pull request merged**
